Top2000/Models/Lijst.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Top2000.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lijst
    {
        public int songid { get; set; }
        public int top2000jaar { get; set; }
        public int positie { get; set; }
    
        public virtual Song Song { get; set; }
        public virtual Top2000Jaar Top2000Jaar1 { get; set; }
    }
}

Top2000/Controllers/ArtiestsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Top2000.Models;
using PagedList;


namespace Top2000.Controllers
{
    public class ArtiestsController : Controller
    {
        private DB_A63478_DeechteTOP2000Entities db = new DB_A63478_DeechteTOP2000Entities();

        // GET: Artiests
        public ActionResult Index(int? page, string sortOrder = "", string searchString = "")
        {
            ViewBag.CurrentFilter = searchString;
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = sortOrder;

            var artiests = db.Artiests.ToList();
            int pageNumber = (page ?? 1);
            int pageSize = 20;
            if(sortOrder == "name_desc")
            {
                artiests = artiests.OrderByDescending(a => a.naam).ToList();
            }
            else if(sortOrder == "name_asc")
            {
                artiests = artiests.OrderBy(a => a.naam).ToList();

            }

            return View(artiests.Where(a => a.naam.ToLower().Contains(searchString.ToLower())).ToList().ToPagedList(pageNumber, pageSize));
        }

        // GET: Artiests/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Artiest artiest = db.Artiests.Find(id);
            if (artiest == null)
            {
                return HttpNotFound();
            }
            return View(artiest);
        }

        // GET: Artiests/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Artiests/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Artiestid,naam")] Artiest artiest)
        {
            if (ModelState.IsValid)
            {
                db.Artiests.Add(artiest);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(artiest);
        }

        // GET: Artiests/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Artiest artiest = db.Artiests.Find(id);
            if (artiest == null)
            {
                return HttpNotFound();
            }
            return View(artiest);
        }

        // POST: Artiests/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Artiestid,naam")] Artiest artiest)
        {
            if (ModelState.IsValid)
            {
                db.Entry(artiest).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(artiest);
        }

        // GET: Artiests/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Artiest artiest = db.Artiests.Find(id);
            if (artiest == null)
            {
                return HttpNotFound();
            }
            return View(artiest);
        }

        // POST: Artiests/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Artiest artiest = db.Artiests.Find(id);
            db.Artiests.Remove(artiest);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Top2000/Controllers/LijstsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Top2000.Models;
using PagedList;



namespace Top2000.Controllers
{
    public class LijstsController : Controller
    {
        private DB_A63478_DeechteTOP2000Entities db = new DB_A63478_DeechteTOP2000Entities();

        // GET: Lijsts
        public ActionResult Index(int? page, int year = 0, string sortOrder = "")
        {
            ViewBag.CurrentFilter = year;
            ViewBag.CurrentSort = sortOrder;

            if (year == 0) year = db.Top2000Jaar.Max(y => y.Jaar);
            ViewBag.year = new SelectList(db.Top2000Jaar, "Jaar", "Titel", year);
            var lijsts = db.Lijsts.Include(l => l.Song).Include(l => l.Top2000Jaar1).Include(l=>l.Song.Artiest).ToList();
            int pageNumber = (page ?? 1);
            int pageSize = 20;

            return View(lijsts.Where(l => l.top2000jaar == year).OrderBy(a => a.positie).ToList().ToPagedList(pageNumber, pageSize));
        }


        // GET: Lijsts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Lijst lijst = db.Lijsts.Find(id);
            if (lijst == null)
            {
                return HttpNotFound();
            }
            return View(lijst);
        }

        // GET: Lijsts/Create
        public ActionResult Create()
        {
            ViewBag.songid = new SelectList(db.Songs, "songid", "titel");
            ViewBag.top2000jaar = new SelectList(db.Top2000Jaar, "Jaar", "Titel");
            return View();
        }

        // POST: Lijsts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "songid,top2000jaar,positie")] Lijst lijst)
        {
            if (ModelState.IsValid)
            {
                db.Lijsts.Add(lijst);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.songid = new SelectList(db.Songs, "songid", "titel", lijst.songid);
            ViewBag.top2000jaar = new SelectList(db.Top2000Jaar, "Jaar", "Titel", lijst.top2000jaar);
            return View(lijst);
        }

        // GET: Lijsts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Lijst lijst = db.Lijsts.Find(id);
            if (lijst == null)
            {
                return HttpNotFound();
            }
            ViewBag.songid = new SelectList(db.Songs, "songid", "titel", lijst.songid);
            ViewBag.top2000jaar = new SelectList(db.Top2000Jaar, "Jaar", "Titel", lijst.top2000jaar);
            return View(lijst);
        }

        // POST: Lijsts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "songid,top2000jaar,positie")] Lijst lijst)
        {
            if (ModelState.IsValid)
            {
                db.Entry(lijst).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.songid = new SelectList(db.Songs, "songid", "titel", lijst.songid);
            ViewBag.top2000jaar = new SelectList(db.Top2000Jaar, "Jaar", "Titel", lijst.top2000jaar);
            return View(lijst);
        }

        // GET: Lijsts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Lijst lijst = db.Lijsts.Find(id);
            if (lijst == null)
            {
                return HttpNotFound();
            }
            return View(lijst);
        }

        // POST: Lijsts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Lijst lijst = db.Lijsts.Find(id);
            db.Lijsts.Remove(lijst);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Top2000/Controllers/SongsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Top2000.Models;
using PagedList;


namespace Top2000.Controllers
{
    public class SongsController : Controller
    {
        private DB_A63478_DeechteTOP2000Entities db = new DB_A63478_DeechteTOP2000Entities();

        // GET: Songs
        public ActionResult Index(int? page, string currentFilter = "", string sortOrder = "", string searchString = "")
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = sortOrder;
            ViewBag.CurrentFilter = searchString;

            var songs = db.Songs.Include(s => s.Artiest).ToList();
            int pageNumber = (page ?? 1);
            int pageSize = 20;
            switch (sortOrder)
            {
                case "titel_desc":
                    songs = songs.OrderByDescending(a => a.titel).ToList();
                    return View(songs.Where(a => a.titel.ToLower().Contains(searchString.ToLower()) ||
                    a.Artiest.naam.ToLower().Contains(searchString.ToLower())).ToList().ToPagedList(pageNumber, pageSize));

                case "titel_asc":
                    songs = songs.OrderBy(a => a.titel).ToList();
                    return View(songs.Where(a => a.titel.ToLower().Contains(searchString.ToLower()) ||
                    a.Artiest.naam.ToLower().Contains(searchString.ToLower())).ToList().ToPagedList(pageNumber, pageSize));

                case "artiest_desc":
                    songs = songs.OrderByDescending(a => a.Artiest.naam).ToList();
                    return View(songs.Where(a => a.titel.ToLower().Contains(searchString.ToLower()) ||
                    a.Artiest.naam.ToLower().Contains(searchString.ToLower())).ToList().ToPagedList(pageNumber, pageSize));

                case "artiest_asc":
                    songs = songs.OrderBy(a => a.Artiest.naam).ToList();
                    return View(songs.Where(a => a.titel.ToLower().Contains(searchString.ToLower()) ||
                    a.Artiest.naam.ToLower().Contains(searchString.ToLower())).ToList().ToPagedList(pageNumber, pageSize));


                case "year_desc":
                    songs = songs.OrderByDescending(a => a.jaar).ToList();
                    return View(songs.Where(a => a.titel.ToLower().Contains(searchString.ToLower()) ||
                    a.Artiest.naam.ToLower().Contains(searchString.ToLower())).ToList().ToPagedList(pageNumber, pageSize));

                case "year_asc":
                    songs = songs.OrderBy(a => a.jaar).ToList();
                    return View(songs.Where(a => a.titel.ToLower().Contains(searchString.ToLower()) ||
                    a.Artiest.naam.ToLower().Contains(searchString.ToLower())).ToList().ToPagedList(pageNumber, pageSize));

                default:
                    songs = songs.OrderBy(a => a.titel).ToList();
                    return View(songs.Where(a => a.titel.ToLower().Contains(searchString.ToLower()) ||
                    a.Artiest.naam.ToLower().Contains(searchString.ToLower())).ToList().ToPagedList(pageNumber, pageSize));
            }
        }
        // GET: Songs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Song song = db.Songs.Find(id);
            if (song == null)
            {
                return HttpNotFound();
            }
            return View(song);
        }

        // GET: Songs/Create
        public ActionResult Create()
        {
            ViewBag.artiestid = new SelectList(db.Artiests, "Artiestid", "naam");
            return View();
        }

        // POST: Songs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "songid,artiestid,titel,jaar")] Song song)
        {
            if (ModelState.IsValid)
            {
                db.Songs.Add(song);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.artiestid = new SelectList(db.Artiests, "Artiestid", "naam", song.artiestid);
            return View(song);
        }

        // GET: Songs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Song song = db.Songs.Find(id);
            if (song == null)
            {
                return HttpNotFound();
            }
            ViewBag.artiestid = new SelectList(db.Artiests, "Artiestid", "naam", song.artiestid);
            return View(song);
        }

        // POST: Songs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "songid,artiestid,titel,jaar")] Song song)
        {
            if (ModelState.IsValid)
            {
                db.Entry(song).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.artiestid = new SelectList(db.Artiests, "Artiestid", "naam", song.artiestid);
            return View(song);
        }

        // GET: Songs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Song song = db.Songs.Find(id);
            if (song == null)
            {
                return HttpNotFound();
            }
            return View(song);
        }

        // POST: Songs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Song song = db.Songs.Find(id);
            db.Songs.Remove(song);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Top2000/Views/Lijsts/Create.cshtml
@model Top2000.Models.Lijst

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Lijst</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.songid, "songid", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("songid", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.songid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.top2000jaar, "top2000jaar", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("top2000jaar", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.top2000jaar, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.positie, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.positie, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.positie, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Top2000/Views/Lijsts/Delete.cshtml
@model Top2000.Models.Lijst

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Lijst</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.positie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.positie)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Song.titel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Song.titel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Top2000Jaar1.Titel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Top2000Jaar1.Titel)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Top2000/Views/Lijsts/Details.cshtml
@model Top2000.Models.Lijst

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Lijst</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.positie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.positie)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Song.titel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Song.titel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Top2000Jaar1.Titel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Top2000Jaar1.Titel)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Top2000/Views/Lijsts/Edit.cshtml
@model Top2000.Models.Lijst

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Lijst</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.songid)

        @Html.HiddenFor(model => model.top2000jaar)

        <div class="form-group">
            @Html.LabelFor(model => model.positie, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.positie, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.positie, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Top2000/Views/Lijsts/Index.cshtml
@model PagedList.IPagedList<Top2000.Models.Lijst>
@using PagedList.Mvc
@{
    ViewBag.Title = "Index";
}

    <h2>
        @Html.DisplayFor(model => model.FirstOrDefault().Top2000Jaar1.Titel)
    </h2>
Hier een lijst kiezen:
@Html.Partial("YearFilter")

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table table-striped table-dark">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().positie)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Song.titel)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Song.Artiest.naam)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.positie)
            </td>
            <td>
                @Html.ActionLink(item.Song.titel, "Details", "Songs", new { id = item.songid}, htmlAttributes: null)
            </td>
            <td>
                @Html.ActionLink(item.Song.Artiest.naam, "Details", "Artiests", new { id = item.Song.artiestid }, htmlAttributes: null)
            </td>
          
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
    }

</table>
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
@Html.PagedListPager(Model, page => Url.Action("Index",
    new { year = ViewBag.CurrentFilter , page = page }))