Top2000/Controllers/StatsController.cs
using Top2000.Controllers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Top2000.Models;
using PagedList;
using PagedList.Mvc;

namespace Top2000.Controllers
{

    public class StatsController : Controller
    {

        public StatsController()
        {
        }
        private DB_A63478_DeechteTOP2000Entities db = new DB_A63478_DeechteTOP2000Entities();

        /// <summary>
        /// Songs made in one of the Top 2000 years
        /// </summary>
        public ActionResult SongsPerYear(int? page, int year = 0, string sortOrder = "")
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = sortOrder;

            ViewBag.CurrentFilter = year;
            if (year == 0) year = db.Top2000Jaar.Max(y => y.Jaar);
            ViewBag.year = new SelectList(db.Top2000Jaar, "Jaar", "Titel", year);
            var list = db.uspSongsPerYear(year).ToList();
            int pageSize = 50;
            int pageNumber = (page ?? 1);
            switch (sortOrder)
            {
                case "titel_desc":
                    list = list.OrderByDescending(a => a.titel).ToList();
                    return View(list.ToList().ToPagedList(pageNumber, pageSize));

                case "titel_asc":
                    list = list.OrderBy(a => a.titel).ToList();
                    return View(list.ToList().ToPagedList(pageNumber, pageSize));

                case "artiest_desc":
                    list = list.OrderByDescending(a => a.naam).ToList();
                    return View(list.ToList().ToPagedList(pageNumber, pageSize));

                case "artiest_asc":
                    list = list.OrderBy(a => a.naam).ToList();
                    return View(list.ToList().ToPagedList(pageNumber, pageSize));
                default:
                    list = list.OrderByDescending(a => a.titel).ToList();
                    return View(list.ToList().ToPagedList(pageNumber, pageSize));
            }
        }
            public ActionResult GoneFromList(int? page, int year = 0, string sortOrder = "")
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = sortOrder;

            ViewBag.CurrentFilter = year;
            if (year == 0) year = db.Top2000Jaar.Max(y => y.Jaar);
            ViewBag.year = new SelectList(db.Top2000Jaar, "Jaar", "Titel", year);
            var list = db.uspGoneFromList(year).ToList();
            int pageSize = 50;
            int pageNumber = (page ?? 1);
            switch (sortOrder)
            {
                case "positie_desc":
                    list = list.OrderByDescending(a => a.positie).ToList();
                    return View(list.ToList().ToPagedList(pageNumber, pageSize));

                case "positie_asc":
                    list = list.OrderBy(a => a.positie).ToList();
                    return View(list.ToList().ToPagedList(pageNumber, pageSize));
                
                default:
                    list = list.OrderByDescending(a => a.titel).ToList();
                    return View(list.ToList().ToPagedList(pageNumber, pageSize));
            }
            }
        public ActionResult LostMoreThan100(int? page, int year = 0, string sortOrder = "")
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = sortOrder;
            ViewBag.CurrentFilter = year;
            if (year == 0) year = db.Top2000Jaar.Max(y => y.Jaar);
            ViewBag.year = new SelectList(db.Top2000Jaar, "Jaar", "Titel", year);

            var list = db.uspSongsLost100Places(year).ToList();

            int pageSize = 50;
            int pageNumber = (page ?? 1);

            switch (sortOrder)
            {
                case "verschil_desc":
                    list = list.OrderByDescending(a => a.verschil).ToList();
                    return View(list.ToList().ToPagedList(pageNumber, pageSize));

                case "verschil_asc":
                    list = list.OrderBy(a => a.verschil).ToList();
                    return View(list.ToList().ToPagedList(pageNumber, pageSize));

                default:
                    list = list.OrderByDescending(a => a.positie).ToList();
                    return View(list.ToList().ToPagedList(pageNumber, pageSize));
            }

        }

        public ActionResult GainedMoreThan100(int? page, int year = 0, string sortOrder = "")
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = sortOrder;
            ViewBag.CurrentFilter = year;
            if (year == 0) year = db.Top2000Jaar.Max(y => y.Jaar);
            ViewBag.year = new SelectList(db.Top2000Jaar, "Jaar", "Titel", year);
            var list = db.uspSongsGained100Places(year).ToList();
            int pageSize = 50;
            int pageNumber = (page ?? 1);
            switch (sortOrder)
            {
                case "verschil_desc":
                    list = list.OrderByDescending(a => a.verschil).ToList();
                    return View(list.ToList().ToPagedList(pageNumber, pageSize));

                case "verschil_asc":
                    list = list.OrderBy(a => a.verschil).ToList();
                    return View(list.ToList().ToPagedList(pageNumber, pageSize));

                default:
                    list = list.OrderByDescending(a => a.positie).ToList();
                    return View(list.ToList().ToPagedList(pageNumber, pageSize));
            }

        }

        public ActionResult SamePlace(int? page, int year = 0)
        {
            ViewBag.CurrentFilter = year;
            if (year == 0) year = db.Top2000Jaar.Max(y => y.Jaar);
            ViewBag.year = new SelectList(db.Top2000Jaar, "Jaar", "Titel", year);

            int pageSize = 50;
            int pageNumber = (page ?? 1);

            return View(db.uspSongsOnSamePosition(year).ToList().ToPagedList(pageNumber, pageSize));
        }

        public ActionResult NewlyListed(int? page, int year = 0)
        {
            ViewBag.CurrentFilter = year;
            if (year == 0) year = db.Top2000Jaar.Max(y => y.Jaar);
            ViewBag.year = new SelectList(db.Top2000Jaar, "Jaar", "Titel", year);

            int pageSize = 50;
            int pageNumber = (page ?? 1);

            return View(db.uspNewlyListed(year).ToList().ToPagedList(pageNumber, pageSize));
        }

        public ActionResult ArtiestWithMuchSongs(int? page, int year = 0)
        {
            ViewBag.CurrentFilter = year;
            if (year == 0) year = db.Top2000Jaar.Max(y => y.Jaar);
            ViewBag.year = new SelectList(db.Top2000Jaar, "Jaar", "Titel", year);

            int pageSize = 50;
            int pageNumber = (page ?? 1);

            return View(db.uspArtistWithMuchSongs(year).ToList().OrderByDescending(a=>a.Aantal_songs).ToPagedList(pageNumber, pageSize));
        }
        public ActionResult GainedPlaces(int? page, int year = 0)
        {
            ViewBag.CurrentFilter = year;
            if (year == 0) year = db.Top2000Jaar.Max(y => y.Jaar);
            ViewBag.year = new SelectList(db.Top2000Jaar, "Jaar", "Titel", year);

            int pageSize = 50;
            int pageNumber = (page ?? 1);

            return View(db.uspSongsGainedPlaces(year).ToList().ToPagedList(pageNumber, pageSize));
        }

        public ActionResult LostPlaces(int? page, int year = 0)
        {
            ViewBag.CurrentFilter = year;
            if (year == 0) year = db.Top2000Jaar.Max(y => y.Jaar);
            ViewBag.year = new SelectList(db.Top2000Jaar, "Jaar", "Titel", year);

            int pageSize = 50;
            int pageNumber = (page ?? 1);

            return View(db.uspSongsLostPlaces(year).ToList().ToPagedList(pageNumber, pageSize));
        }


    }
}

Top2000/Views/Stats/ArtiestWithMuchSongs.cshtml
@model PagedList.IPagedList<Top2000.Models.uspArtistWithMuchSongs_Result>
@using PagedList.Mvc


@{
    ViewBag.Title = "Index";
    <h2>Artiesten die 20+ nummers in de jaar @Html.DisplayFor(model => model.FirstOrDefault().top2000jaar) lijst hebben staan </h2>
}

@Html.Partial("YearFilter")

    <table class="table table-striped table-dark " id="yearlist">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.FirstOrDefault().naam)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.FirstOrDefault().Aantal_songs)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.FirstOrDefault().top2000jaar)
                <th></th>
            </tr>

        </thead>

        <tbody>

            @foreach (var item in Model)
            {
                <tr class="listRow">
                    <td>
                        @Html.DisplayFor(modelItem => item.naam)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Aantal_songs)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.top2000jaar)
                    </td>
                </tr>
            }

        </tbody>

    </table>
    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
    @Html.PagedListPager(Model, page => Url.Action("ArtistWithMuchSongs", "Stats",
        new { year = ViewBag.CurrentFilter, page = page }))

Top2000/Views/Stats/GainedMoreThan100.cshtml
@model PagedList.IPagedList<Top2000.Models.uspSongsGained100Places_Result>
@using PagedList.Mvc


@{
    ViewBag.Title = "Index";
    <h2>Songs die meer dan 100 plaatsen zijn gestegen tov het voorgaande jaar</h2>
}

@Html.Partial("YearFilter")


<table class="table table-striped table-dark " id="yearlist">
    <thead>

        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().titel)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().naam)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().positie)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().vorig_jaar)
            </th>
            <th>
                @Html.ActionLink(Html.DisplayNameFor(model => model.FirstOrDefault().verschil).ToString(),
                                             "GainedMoreThan100", new
                                             {
                                                 sortOrder = ViewBag.NameSortParm == "verschil_asc" ? "verschil_desc" : "verschil_asc",
                                                 year = ViewBag.CurrentFilter

                                             })
            </th>



            <th></th>
        </tr>

    </thead>

    <tbody>

        @foreach (var item in Model)
        {
            <tr class="listRow">
                <td>
                    @Html.DisplayFor(modelItem => item.titel)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.naam)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.positie)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.vorig_jaar)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.verschil)
                </td>
            </tr>
        }

    </tbody>

</table>
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
@Html.PagedListPager(Model, page => Url.Action("GainedMoreThan100", "Stats",
    new { year = ViewBag.CurrentFilter, page = page }))

Top2000/Views/Stats/GainedPlaces.cshtml
@model PagedList.IPagedList<Top2000.Models.uspSongsGainedPlaces_Result>
@using PagedList.Mvc


@{
    ViewBag.Title = "Index";
    <h2>Songs die zijn gestegen tov het voorgaande jaar</h2>
}

@Html.Partial("YearFilter")


<table class="table table-striped table-dark " id="yearlist">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().titel)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().naam)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().positie)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().vorig_jaar)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().verschil)
            </th>

            <th></th>
        </tr>

    </thead>

    <tbody>

        @foreach (var item in Model)
        {
            <tr class="listRow">
                <td>
                    @Html.DisplayFor(modelItem => item.titel)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.naam)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.positie)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.vorig_jaar)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.verschil)
                </td>
            </tr>
        }

    </tbody>

</table>
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
@Html.PagedListPager(Model, page => Url.Action("GainedPlaces", "Stats",
    new { year = ViewBag.CurrentFilter, page = page }))

Top2000/Views/Stats/GoneFromList.cshtml
@model PagedList.IPagedList<Top2000.Models.uspGoneFromList_Result>
@using PagedList.Mvc

@{
    ViewBag.Title = "Index";
    <h2>Alle songs die uit de jaarlijst zijn gevallen t.o.v. het vorige jaar</h2>
}

@Html.Partial("YearFilter")


<table class="table table-striped table-dark " id="yearlist">
    <thead>

        <tr>
            <th>
                @Html.ActionLink(Html.DisplayNameFor(model => model.FirstOrDefault().positie).ToString(),
"GoneFromList", new
{
   sortOrder = ViewBag.NameSortParm == "positie_asc" ? "positie_desc" : "positie_asc",
   year = ViewBag.CurrentFilter

})
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().naam)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().titel)
            </th>

            <th></th>
        </tr>

    </thead>

    <tbody>

        @foreach (var item in Model)
        {
            <tr class="listRow">
                <td class="differenceCell">
                    @Html.DisplayFor(modelItem => item.positie)
                </td>
                <td class="positie">
                    @Html.DisplayFor(modelItem => item.naam)
                </td>
                <td class="differenceCell">
                    @Html.DisplayFor(modelItem => item.titel)
                </td>

            </tr>

        }

    </tbody>

</table>
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
@Html.PagedListPager(Model, page => Url.Action("GoneFromList", "Stats",
    new { year = ViewBag.CurrentFilter, page = page }))

Top2000/Views/Stats/LostMoreThan100.cshtml
@model PagedList.IPagedList<Top2000.Models.uspSongsLost100Places_Result>
@using PagedList.Mvc


@{
    ViewBag.Title = "Index";
    <h2>Songs die meer dan 100 plaatsen zijn gedaald tov het voorgaande jaar</h2>
}

@Html.Partial("YearFilter")


<table class="table table-striped table-dark " id="yearlist">
    <thead>

        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().titel)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().naam)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().positie)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().vorig_jaar)
            </th>
            <th>
                @Html.ActionLink(Html.DisplayNameFor(model => model.FirstOrDefault().verschil).ToString(),
                               "LostMoreThan100", new
                               {
                                   sortOrder = ViewBag.NameSortParm == "verschil_asc" ? "verschil_desc" : "verschil_asc",
                                   year = ViewBag.CurrentFilter

                               })
            </th>



            <th></th>
        </tr>

    </thead>

    <tbody>

        @foreach (var item in Model)
        {
            <tr class="listRow">
                <td>
                    @Html.DisplayFor(modelItem => item.titel)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.naam)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.positie)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.vorig_jaar)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.verschil)
                </td>
            </tr>
        }

    </tbody>

</table>
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
@Html.PagedListPager(Model, page => Url.Action("LostMoreThan100", "Stats",
    new { year = ViewBag.CurrentFilter, page = page }))

Top2000/Views/Stats/LostPlaces.cshtml
@model PagedList.IPagedList<Top2000.Models.uspSongsLostPlaces_Result>
@using PagedList.Mvc


@{
    ViewBag.Title = "Index";
    <h2>Songs die zijn gedaald tov het voorgaande jaar</h2>
}

@Html.Partial("YearFilter")


<table class="table table-striped table-dark " id="yearlist">
    <thead>

        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().titel)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().naam)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().positie)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().vorig_jaar)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().verschil)
            </th>



            <th></th>
        </tr>

    </thead>

    <tbody>

        @foreach (var item in Model)
        {
            <tr class="listRow">
                <td>
                    @Html.DisplayFor(modelItem => item.titel)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.naam)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.positie)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.vorig_jaar)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.verschil)
                </td>
            </tr>
        }

    </tbody>

</table>
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
@Html.PagedListPager(Model, page => Url.Action("LostPlaces", "Stats",
    new { year = ViewBag.CurrentFilter, page = page }))

Top2000/Views/Stats/NewlyListed.cshtml
@model PagedList.IPagedList<Top2000.Models.uspNewlyListed_Result>
@using PagedList.Mvc


@{
    ViewBag.Title = "Index";
    <h2>All new songs in yearlist</h2>
}

@Html.Partial("YearFilter")


<table class="table table-striped table-dark " id="yearlist">
    <thead>

        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().titel)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().naam)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().positie)
            </th>
            <th></th>
        </tr>

    </thead>

    <tbody>

        @foreach (var item in Model)
        {
            <tr class="listRow">
                <td>
                    @Html.DisplayFor(modelItem => item.titel)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.naam)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.positie)
                </td>
            </tr>
        }

    </tbody>

</table>
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
@Html.PagedListPager(Model, page => Url.Action("NewlyListed", "Stats",
    new { year = ViewBag.CurrentFilter, page = page }))

Top2000/Views/Stats/SamePlace.cshtml
@model PagedList.IPagedList<Top2000.Models.uspSongsOnSamePosition_Result>
@using PagedList.Mvc


@{
    ViewBag.Title = "Index";
    <h2>Songs die op dezelfde plek staan als het vorige jaar</h2>
}

@Html.Partial("YearFilter")


<table class="table table-striped table-dark " id="yearlist">
    <thead>

        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().titel)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().naam)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().positie)
            </th>

            <th></th>
        </tr>

    </thead>

    <tbody>

        @foreach (var item in Model)
        {
            <tr class="listRow">
                <td>
                    @Html.DisplayFor(modelItem => item.titel)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.naam)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.positie)
                </td>
            </tr>
        }

    </tbody>

</table>
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
@Html.PagedListPager(Model, page => Url.Action("SamePlace", "Stats",
    new { year = ViewBag.CurrentFilter, page = page }))

Top2000/Views/Stats/SongsPerYear.cshtml
@model IPagedList<Top2000.Models.uspSongsPerYear_Result>
@using PagedList;
@using PagedList.Mvc

@{
    ViewBag.Title = "Index";
    <h2>Alle songs die in een bepaald jaar zijn uitgebracht</h2>
}

@Html.Partial("YearFilter")


<table class="table table-striped table-dark " id="yearlist">
    <thead>

        <tr>

            <th>
                @Html.ActionLink(Html.DisplayNameFor(model => model.FirstOrDefault().naam).ToString(),
               "SongsPerYear", new
               {
                   sortOrder = ViewBag.NameSortParm == "artiest_asc" ? "artiest_desc" : "artiest_asc",
                   year = ViewBag.CurrentFilter

               })
            </th>
            <th>
                @Html.ActionLink(Html.DisplayNameFor(model => model.FirstOrDefault().titel).ToString(),
               "SongsPerYear", new
               {
                   sortOrder = ViewBag.NameSortParm == "titel_asc" ? "titel_desc" : "titel_asc",
                   year = ViewBag.CurrentFilter
               })
            </th>
            <th></th>
        </tr>

    </thead>

    <tbody>

        @foreach (var item in Model)
        {
            <tr class="listRow">

                <td class="positie">
                    @Html.DisplayFor(modelItem => item.naam)
                </td>
                <td class="differenceCell">
                    @Html.DisplayFor(modelItem => item.titel)
                </td>
            </tr>

        }

    </tbody>

</table>
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
@Html.PagedListPager(Model, page => Url.Action("SongsPerYear", "Stats",
    new { year = ViewBag.CurrentFilter, page = page }))